[package]
name = "yxml"
version = "0.1.0"
authors = ["Jakub Kądziołka <kuba@kadziolka.net>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A parser for Isabelle's YXML serialization format"

[dependencies]
